/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Client.SocketFunction;
import Entity.BuyProduct;
import Entity.Food;
import Handler.FoodHandler;
import Handler.FoodOrderHandler;
import Handler.OrderHandler;
import Server.ConnectionDatabase;
import Server.FormatData;
import com.google.gson.Gson;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.sql.*;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author ranco
 */
public class ShowProduct extends javax.swing.JFrame {

    /**
     * Creates new form ShowProduct
     *
     * @param ID
     * @throws java.io.IOException
     */
    private int orderId;
    private SocketFunction socketFunction;

    public ShowProduct(int orderId, SocketFunction socketFunction) throws IOException {
        this.orderId = orderId;
        this.socketFunction = socketFunction;
        initComponents();
        show_menu();
//        show_buy_product();
//        populateJTable(new QueryForProduct().BindTable(user, pass));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        nameVar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        priceVar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AddBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        FoodOrderTable = new javax.swing.JTable();
        confirmBtn = new javax.swing.JButton();
        quantityVar = new javax.swing.JSpinner();
        cardVar = new javax.swing.JRadioButton();
        cashVar = new javax.swing.JRadioButton();
        totalMoney = new javax.swing.JLabel();
        allPaymentVar2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        welcomeUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1165, 720));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProductTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Description", "Price", "Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductTable.setGridColor(new java.awt.Color(153, 153, 255));
        ProductTable.setShowGrid(false);
        ProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductTable);
        if (ProductTable.getColumnModel().getColumnCount() > 0) {
            ProductTable.getColumnModel().getColumn(0).setPreferredWidth(0);
        }

        nameVar.setEditable(false);
        nameVar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameVar.setForeground(new java.awt.Color(153, 153, 255));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 255));
        jLabel7.setText("Shopping Cart");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Price:");

        priceVar.setEditable(false);
        priceVar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        priceVar.setForeground(new java.awt.Color(153, 153, 255));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 255));
        jLabel8.setText("Quantity:");

        AddBtn.setBackground(new java.awt.Color(204, 204, 255));
        AddBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AddBtn.setText("Add");
        AddBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddBtn.setBorderPainted(false);
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });

        FoodOrderTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FoodOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT", "PRICE", "QUANTITY"
            }
        ));
        jScrollPane4.setViewportView(FoodOrderTable);

        confirmBtn.setBackground(new java.awt.Color(0, 204, 51));
        confirmBtn.setText("Confirm");
        confirmBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmBtnMouseClicked(evt);
            }
        });

        quantityVar.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        quantityVar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quantityVarStateChanged(evt);
            }
        });

        buttonGroup1.add(cardVar);
        cardVar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cardVar.setText("By Card");
        cardVar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardVarMouseClicked(evt);
            }
        });
        cardVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardVarActionPerformed(evt);
            }
        });

        buttonGroup1.add(cashVar);
        cashVar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cashVar.setSelected(true);
        cashVar.setText("By cash");
        cashVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashVarActionPerformed(evt);
            }
        });

        totalMoney.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        totalMoney.setForeground(new java.awt.Color(153, 153, 255));
        totalMoney.setText("0");

        allPaymentVar2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        allPaymentVar2.setForeground(new java.awt.Color(153, 153, 255));
        allPaymentVar2.setText("Total:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cashVar)
                                .addGap(90, 90, 90)
                                .addComponent(cardVar)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(allPaymentVar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(109, 109, 109))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(nameVar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(priceVar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(quantityVar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameVar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceVar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityVar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(allPaymentVar2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cashVar)
                            .addComponent(cardVar))
                        .addGap(18, 18, 18)
                        .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PEELADAZ");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Back");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        welcomeUser.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        welcomeUser.setForeground(new java.awt.Color(255, 255, 255));
        welcomeUser.setText("Welcome to our restaurant");
        welcomeUser.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                welcomeUserInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addComponent(welcomeUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(487, 487, 487)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(welcomeUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(280, 280, 280)
                    .addComponent(jLabel4)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1212, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    class CellRenderer implements TableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column) {

            TableColumn tb = ProductTable.getColumn("Image");
            tb.setMaxWidth(60);
            tb.setMinWidth(60);

            ProductTable.setRowHeight(60);

            return (Component) value;
        }

    }

    private void cashVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashVarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cashVarActionPerformed

    private void confirmBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmBtnMouseClicked

        if (cashVar.isSelected() == true) {
            Congrats congrats = new Congrats();
            congrats.setVisible(true);
//            this.setVisible(false);
        } else if(cardVar.isSelected() == true){
            PaymentByCard paymen = new PaymentByCard(orderId, socketFunction);
            paymen.setVisible(true);
//            this.setVisible(false);
        }

    }//GEN-LAST:event_confirmBtnMouseClicked

    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked
        // TODO add your handling code here:
        String nameFood = nameVar.getText();
        String priceFood = priceVar.getText();
        String quantityStr = quantityVar.getValue().toString();
        System.out.println("quantity: " + quantityStr);
//        String quanVar = quantityVar.getText();
        System.out.println("name: " + nameFood + " | price: " + priceFood + " | quantity: " + quantityStr);

//        int orderId = formatData.orderId;
        int foodId = OrderHandler.getFoodIdByName(nameFood);
        int quantity = (int) quantityVar.getValue();
        System.out.println("orderId: " + this.orderId + ", foodId: " + foodId + ", quantity: " + quantity);
        try {
            socketFunction.sendOneFood(foodId, orderId, quantity);
            socketFunction.getTotalMoney(orderId);
//        OrderHandler.insertOneProduct(foodId, orderId, quantity);

        } catch (IOException ex) {
            Logger.getLogger(ShowProduct.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            show_buy_product();
            showMoney();
        } catch (IOException ex) {
            Logger.getLogger(ShowProduct.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_AddBtnMouseClicked

    private void ProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTableMouseClicked
        // TODO add your handling code here:
        int Myindex = ProductTable.getSelectedRow();
//        nameVar.setText(ProductTable.getValueAt(Myindex, 5).toString());
        nameVar.setText(ProductTable.getValueAt(Myindex, 1).toString());
        priceVar.setText(ProductTable.getValueAt(Myindex, 3).toString());

    }//GEN-LAST:event_ProductTableMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked
//    private String getTypee(String type){
//        
//    }
    private void cardVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardVarActionPerformed

    }//GEN-LAST:event_cardVarActionPerformed

    private void quantityVarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quantityVarStateChanged
        // TODO add your handling code here:
        String quantity = quantityVar.getValue().toString();
        System.out.println("quantity: " + quantity);
    }//GEN-LAST:event_quantityVarStateChanged

    private void welcomeUserInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_welcomeUserInputMethodTextChanged
        // TODO add your handling code here:
//        welcomeUser.setText("Welcome " + );
    }//GEN-LAST:event_welcomeUserInputMethodTextChanged

    private void clearTable() {
        ((DefaultTableModel) ProductTable.getModel()).setNumRows(0);
    }

    private void cardVarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardVarMouseClicked
        // TODO add your handling code here:
//        PaymentByCard paymen = new PaymentByCard(orderId, socketFunction);
//        paymen.setVisible(true);
    }//GEN-LAST:event_cardVarMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        Login open = new Login();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private BufferedImage showIMG(String url) {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(url)); // eventually C:\\ImageTest\\pic2.jpg
        } catch (IOException e) {
            e.printStackTrace();
        }
        return img;
    }

    private void show_menu() {
        ArrayList<Food> listFood = FoodHandler.getAllMenu();
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
        Object[] newIdentifiers = new Object[]{"Id", "Name", "Discription", "Price", "Image"};
        ProductTable.setFillsViewportHeight(true);
        ProductTable.getColumn("Image").setCellRenderer(new CellRenderer());

        for (int i = 0; i < listFood.size(); i++) {
            newIdentifiers[0] = listFood.get(i).getFoodId();
            newIdentifiers[1] = listFood.get(i).getFoodName();
            newIdentifiers[2] = listFood.get(i).getFoodDescription();
            newIdentifiers[3] = listFood.get(i).getFoodCost();
            JLabel imageLabel = new JLabel();
            ImageIcon imageicon = new ImageIcon(listFood.get(i).getFoodUrlIMG());
            Image img = imageicon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
//            System.out.println(">>>>> "+ listFood.get(i).getFoodUrlIMG());
            imageLabel.setIcon(new ImageIcon(img));
            newIdentifiers[4] = imageLabel;

            model.addRow(newIdentifiers);
        }

    }

    public void showMoney() throws IOException {
        String total = socketFunction.getTotalMoney(orderId);
        System.out.println("total client: " + total);
        totalMoney.setText(total + " VND");
    }

    private void show_buy_product() throws IOException {
        String result = socketFunction.getAllFoodorder(orderId);
        System.out.println(result);
        String[] listProducts = result.split(" ");
        ArrayList<BuyProduct> listBuyProduct = new ArrayList<>();

        for (String a : listProducts) {
            System.out.println(a);
            Gson gson = new Gson();
            BuyProduct tmp = gson.fromJson(a, BuyProduct.class);
            System.out.println(tmp.getName() + " | " + tmp.getCost() + " | " + tmp.getQuantity());
            listBuyProduct.add(tmp);
        }

        DefaultTableModel model = (DefaultTableModel) FoodOrderTable.getModel();
        model.setRowCount(0);
        Object[] row = new Object[3];

        for (int i = 0; i < listBuyProduct.size(); i++) {
            row[0] = listBuyProduct.get(i).getName();
            row[1] = listBuyProduct.get(i).getCost();
            row[2] = listBuyProduct.get(i).getQuantity();
            model.addRow(row);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JTable FoodOrderTable;
    private javax.swing.JTable ProductTable;
    private javax.swing.JLabel allPaymentVar2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cardVar;
    private javax.swing.JRadioButton cashVar;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nameVar;
    private javax.swing.JTextField priceVar;
    private javax.swing.JSpinner quantityVar;
    private javax.swing.JLabel totalMoney;
    private javax.swing.JLabel welcomeUser;
    // End of variables declaration//GEN-END:variables
}
